# Numpy  آشنایی و کار با کتابخانه  

In [ ]:
import numpy as np

x1 = np.random.randint(10, size=6) # یک بعدی array
x2 = np.random.randint(10, size=(3, 4)) # دو بعدی array
x3 = np.random.randint(10, size=(3, 4, 5)) # سه بعدی array

In [3]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]], dtype=int32)

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print("dtype:", x3.dtype)

dtype: int32


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [7]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [8]:
x1[0]

np.int32(5)

In [9]:
x1[-2]

np.int32(7)

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [11]:
x2[0, 0]

np.int32(3)

In [12]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [13]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)

In [14]:
# subarray دسترسی به

In [15]:
# یک بعدی

In [16]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
x[5:]

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]

array([4, 5, 6])

In [20]:
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
x[1::2]

array([1, 3, 5, 7, 9])

In [22]:
x[::-1]# تمام مقادیر برعکس می شوند

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
# چند بعدی

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [25]:
x2[:2, :3]# دو سطر، سه ستون

array([[12,  5,  2],
       [ 7,  6,  8]], dtype=int32)

In [26]:
x2[:3, ::2]# تمامی سطرها، ستون ها یکی در میان

array([[12,  2],
       [ 7,  8],
       [ 1,  7]], dtype=int32)

In [27]:
x2[::-1, ::-1] #  همه با هم برعکس

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]], dtype=int32)

In [28]:
print(x2[:, 0]) # اولین ستون x2

[12  7  1]


In [29]:
print(x2[0]) #  x2[0, :]  برابر با

[12  5  2  4]


In [30]:
# Reshaping of Arrays

In [31]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
x = np.array([1, 2, 3])
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [33]:
#Array Concatenation and Splitting

In [34]:
#1.Concatenation of arrays

In [6]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [7]:
z = [99, 99, 99]
print(np.concatenate([x, y, z])) #بدون افزایش بعد

[ 1  2  3  3  2  1 99 99 99]


In [8]:
np.vstack([x,y]) #افزایش بعد

array([[1, 2, 3],
       [3, 2, 1]])

In [37]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [38]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [39]:
y = np.array([[99],
              [99]])

In [40]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [41]:
#Splitting of arrays

In [42]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

[1 2 3] [99 99  3] [2 1]


In [43]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [45]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Numpy استفاده از عملگرها در   
Operator                       ufunc Description
+ np.add                        (e.g., 1 + 1 = 2)
- np.subtract                   (e.g., 3 - 2 = 1)
- np.negative                      (e.g., -2)
* np.multiply                   (e.g., 2 * 3 = 6)
/ np.divide                     (e.g., 3 / 2 = 1.5)
// np.floor_divide              (e.g., 3 // 2 = 1)
** np.power                     (e.g., 2 ** 3 = 8)
% np.mod                        (e.g., 9 % 4 = 1)

In [46]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print(-(0.5*x + 1) ** 2)
np.add(x, 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[-1.   -2.25 -4.   -6.25]


array([2, 3, 4, 5])

In [47]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [48]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [ ]:
data= np.random.random(100)
data

array([0.65279032, 0.63505887, 0.99529957, 0.58185033, 0.41436859,
       0.4746975 , 0.6235101 , 0.33800761, 0.67475232, 0.31720174,
       0.77834548, 0.94957105, 0.66252687, 0.01357164, 0.6228461 ,
       0.67365963, 0.971945  , 0.87819347, 0.50962438, 0.05571469,
       0.45115921, 0.01998767, 0.44171092, 0.97958673, 0.35944446,
       0.48089353, 0.68866118, 0.88047589, 0.91823547, 0.21682214,
       0.56518887, 0.86510256, 0.50896896, 0.91672295, 0.92115761,
       0.08311249, 0.27771856, 0.0093567 , 0.84234208, 0.64717414,
       0.84138612, 0.26473016, 0.39782075, 0.55282148, 0.16494046,
       0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644,
       0.43328806, 0.75610669, 0.39609828, 0.89603839, 0.63892108,
       0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191,
       0.7670237 , 0.41182014, 0.67543908, 0.24979628, 0.31321833,
       0.96541622, 0.58846509, 0.65966841, 0.53320625, 0.23053302,
       0.39486929, 0.61880856, 0.47486752, 0.47013219, 0.71607

In [ ]:
np.min(data), np.max(data)

(np.float64(0.009356704856532616), np.float64(0.9952995676778876))

In [52]:
# نمونه Aggregation

In [53]:
M = np.random.random((3, 4))
print(M)

[[0.16684751 0.77905102 0.8649333  0.41139672]
 [0.13997259 0.03322239 0.98257496 0.37329075]
 [0.42007537 0.05058812 0.36549611 0.01662797]]


In [54]:
M.sum()

np.float64(4.604076798225436)

In [55]:
M.min(axis=0)

array([0.13997259, 0.03322239, 0.36549611, 0.01662797])

In [56]:
M.max(axis=1)

array([0.8649333 , 0.98257496, 0.42007537])

In [57]:
M.argmax()

np.int64(6)

In [58]:
# Sorting Arrays

In [60]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [61]:
print(np.sort(x))

[1 2 3 4 5]


In [62]:
X = np.random.randint(0, 10, (4, 6))
X

array([[7, 7, 5, 1, 2, 2],
       [8, 1, 5, 8, 4, 0],
       [2, 5, 5, 0, 8, 1],
       [1, 0, 3, 8, 8, 4]], dtype=int32)

In [63]:
# sort each column of X
np.sort(X, axis=0)

array([[1, 0, 3, 0, 2, 0],
       [2, 1, 5, 1, 4, 1],
       [7, 5, 5, 8, 8, 2],
       [8, 7, 5, 8, 8, 4]], dtype=int32)

In [64]:
# sort each row of X
np.sort(X, axis=1)

array([[1, 2, 2, 5, 7, 7],
       [0, 1, 4, 5, 8, 8],
       [0, 1, 2, 5, 5, 8],
       [0, 1, 3, 4, 8, 8]], dtype=int32)